"""add requested article status, modify channel unique names

Revision ID: 685cfdcec9dd
Revises: 9d3f97f0bb4a
Create Date: 2019-12-03 17:57:09.710099

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '685cfdcec9dd'
down_revision = '9d3f97f0bb4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Channel', sa.Column('status', sa.SmallInteger(), server_default='1', nullable=False))
    op.drop_index('ix_Channel_name', table_name='Channel')
    op.create_index(op.f('ix_Channel_name'), 'Channel', ['name'], unique=True)
    op.drop_column('Channel', 'is_public')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Channel', sa.Column('is_public', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_Channel_name'), table_name='Channel')
    op.create_index('ix_Channel_name', 'Channel', ['name'], unique=False)
    op.drop_column('Channel', 'status')
    # ### end Alembic commands ###
