"""comment table and relations

Revision ID: 77376cdb2019
Revises: 055989a7f82f
Create Date: 2019-12-01 03:53:32.068870

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '77376cdb2019'
down_revision = '055989a7f82f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Comment',
    sa.Column('coid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('comment_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('comment_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comment_user_uid', sa.Integer(), nullable=True),
    sa.Column('comment_article_aid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_article_aid'], ['Article.aid'], ),
    sa.ForeignKeyConstraint(['comment_user_uid'], ['User.uid'], ),
    sa.PrimaryKeyConstraint('coid')
    )
    op.add_column('Favorite', sa.Column('fav_article_aid', sa.Integer(), nullable=True))
    op.add_column('Favorite', sa.Column('fav_user_uid', sa.Integer(), nullable=True))
    op.drop_constraint('favorite_ibfk_1', 'Favorite', type_='foreignkey')
    op.drop_constraint('favorite_ibfk_2', 'Favorite', type_='foreignkey')
    op.create_foreign_key(None, 'Favorite', 'Article', ['fav_article_aid'], ['aid'])
    op.create_foreign_key(None, 'Favorite', 'User', ['fav_user_uid'], ['uid'])
    op.drop_column('Favorite', 'article_aid')
    op.drop_column('Favorite', 'user_uid')
    op.add_column('Subscription', sa.Column('sub_channel_cid', sa.Integer(), nullable=True))
    op.add_column('Subscription', sa.Column('sub_user_uid', sa.Integer(), nullable=True))
    op.drop_constraint('subscription_ibfk_2', 'Subscription', type_='foreignkey')
    op.drop_constraint('subscription_ibfk_1', 'Subscription', type_='foreignkey')
    op.create_foreign_key(None, 'Subscription', 'Channel', ['sub_channel_cid'], ['cid'])
    op.create_foreign_key(None, 'Subscription', 'User', ['sub_user_uid'], ['uid'])
    op.drop_column('Subscription', 'channel_cid')
    op.drop_column('Subscription', 'user_uid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Subscription', sa.Column('user_uid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('Subscription', sa.Column('channel_cid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Subscription', type_='foreignkey')
    op.drop_constraint(None, 'Subscription', type_='foreignkey')
    op.create_foreign_key('subscription_ibfk_1', 'Subscription', 'Channel', ['channel_cid'], ['cid'])
    op.create_foreign_key('subscription_ibfk_2', 'Subscription', 'User', ['user_uid'], ['uid'])
    op.drop_column('Subscription', 'sub_user_uid')
    op.drop_column('Subscription', 'sub_channel_cid')
    op.add_column('Favorite', sa.Column('user_uid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('Favorite', sa.Column('article_aid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Favorite', type_='foreignkey')
    op.drop_constraint(None, 'Favorite', type_='foreignkey')
    op.create_foreign_key('favorite_ibfk_2', 'Favorite', 'User', ['user_uid'], ['uid'])
    op.create_foreign_key('favorite_ibfk_1', 'Favorite', 'Article', ['article_aid'], ['aid'])
    op.drop_column('Favorite', 'fav_user_uid')
    op.drop_column('Favorite', 'fav_article_aid')
    op.drop_table('Comment')
    # ### end Alembic commands ###
