"""empty message

Revision ID: 99a13e2fa031
Revises: 77376cdb2019
Create Date: 2019-12-01 20:33:00.518624

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '99a13e2fa031'
down_revision = '77376cdb2019'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('sub_user_uid', sa.Integer(), nullable=True),
    sa.Column('sub_channel_cid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sub_channel_cid'], ['Channel.cid'], ),
    sa.ForeignKeyConstraint(['sub_user_uid'], ['User.uid'], )
    )
    op.create_table('comments',
    sa.Column('coid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('comment_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('comment_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comment_user_uid', sa.Integer(), nullable=True),
    sa.Column('comment_article_aid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_article_aid'], ['Article.aid'], ),
    sa.ForeignKeyConstraint(['comment_user_uid'], ['User.uid'], ),
    sa.PrimaryKeyConstraint('coid')
    )
    op.create_table('favorites',
    sa.Column('fav_user_uid', sa.Integer(), nullable=True),
    sa.Column('fav_article_aid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fav_article_aid'], ['Article.aid'], ),
    sa.ForeignKeyConstraint(['fav_user_uid'], ['User.uid'], )
    )
    op.drop_table('Subscription')
    op.drop_table('Comment')
    op.drop_table('Favorite')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Favorite',
    sa.Column('fav_article_aid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('fav_user_uid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fav_article_aid'], ['Article.aid'], name='favorite_ibfk_1'),
    sa.ForeignKeyConstraint(['fav_user_uid'], ['User.uid'], name='favorite_ibfk_2'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Comment',
    sa.Column('coid', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('body', mysql.TEXT(), nullable=False),
    sa.Column('comment_created', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('comment_updated', mysql.DATETIME(), nullable=True),
    sa.Column('comment_user_uid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('comment_article_aid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['comment_article_aid'], ['Article.aid'], name='comment_ibfk_1'),
    sa.ForeignKeyConstraint(['comment_user_uid'], ['User.uid'], name='comment_ibfk_2'),
    sa.PrimaryKeyConstraint('coid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Subscription',
    sa.Column('sub_channel_cid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('sub_user_uid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sub_channel_cid'], ['Channel.cid'], name='subscription_ibfk_1'),
    sa.ForeignKeyConstraint(['sub_user_uid'], ['User.uid'], name='subscription_ibfk_2'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('favorites')
    op.drop_table('comments')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
