"""adjusted relationships

Revision ID: 9d3f97f0bb4a
Revises: 99a13e2fa031
Create Date: 2019-12-01 21:45:46.845891

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9d3f97f0bb4a'
down_revision = '99a13e2fa031'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'comment_article_aid',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('comments', 'comment_user_uid',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'comment_user_uid',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('comments', 'comment_article_aid',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###
